export type Profile = {
    username: string,
    instagram: string | null,
    twitter: string | null,
    website: string | null,
    description: string | null,
    hero_picture: string | null,
    picture: string | null,
    email: string | null,
    tiktok: string | null,
    twitch: string | null,
    digisafe_1: string | null,
    digisafe_2: string | null,
    digisafe_3: string | null,
    digisafe_4: string | null,
    digisafe_5: string | null,
    digisafe_6: string | null,
    digisafe_7: string | null,
    digisafe_8: string | null,
    operator: string | null,
};
